server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: payout-service
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/gigshield}
      auto-index-creation: true
  
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          worker.registered:com.gigshield.common.events.WorkerRegisteredEvent,
          policy.purchased:com.gigshield.common.events.PolicyPurchasedEvent,
          environment.disruption:com.gigshield.common.events.EnvironmentDisruptionEvent,
          claim.initiated:com.gigshield.common.events.ClaimInitiatedEvent,
          claim.validated:com.gigshield.common.events.ClaimValidatedEvent,
          claim.approved:com.gigshield.common.events.ClaimApprovedEvent,
          payout.completed:com.gigshield.common.events.PayoutCompletedEvent
    consumer:
      group-id: payout-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.gigshield.common.events
        spring.json.type.mapping: >
          worker.registered:com.gigshield.common.events.WorkerRegisteredEvent,
          policy.purchased:com.gigshield.common.events.PolicyPurchasedEvent,
          environment.disruption:com.gigshield.common.events.EnvironmentDisruptionEvent,
          claim.initiated:com.gigshield.common.events.ClaimInitiatedEvent,
          claim.validated:com.gigshield.common.events.ClaimValidatedEvent,
          claim.approved:com.gigshield.common.events.ClaimApprovedEvent,
          payout.completed:com.gigshield.common.events.PayoutCompletedEvent

payment:
  razorpay:
    key-id: ${RAZORPAY_KEY_ID:rzp_test_demo}
    key-secret: ${RAZORPAY_KEY_SECRET:demo_secret}
    base-url: https://api.razorpay.com/v1
  
  retry:
    max-attempts: 3
    delay-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.gigshield: DEBUG
