server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: fraud-detection
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://charan:charan825@myatlasclusteredu.eqstcqn.mongodb.net/?appName\=myAtlasClusterEDU}
      auto-index-creation: true
      database: gig-shield
  
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: fraud-detection
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.gigshield.common.events

fraud:
  thresholds:
    fraud-score-max: 0.7
    duplicate-claim-hours: 24
    location-radius-km: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.gigshield: DEBUG
